### ISSUE TITLE
while giving header or body to http. mock type 'Null' is not a subtype of type 'Future<Response>' this error coming

### ISSUE THREAD

**Issue by fimaljo** [felangel/mocktail#224] opened 2023-12-29 17:16 UTC
type 'Null' is not a subtype of type 'Future<Response>'
test\webservice\login\feedback_request_test.dart 14:7              MockClient.post
feedback_request_test.dart:14
package:choys/src/webservice/feedback/feedback_request.dart 24:35  FeedbackRequest.createFeedback
test\webservice\login\feedback_request_test.dart 81:51             main.<fn>.<fn>

**Comment by maxstubbersfield** [comment] 2024-01-02 14:41
Hi there, are you adding the headers and/or body to the stub response of the MockClient?

`when(() => httpClient.post(any(), headers: any(named: 'headers'), body: any(named: 'body'))).thenAnswer((_) async => response);`

**Comment by fimaljo** [comment] 2024-01-02 14:55
yes also i used mockito while using that this is the error MissingStubError: 'post'
No stub was found which matches the arguments of this method call:
post(https://feedback/create, {headers: null, body: null, encoding: null})
but there is no miss match

**Comment by felangel** [comment] 2024-04-20 03:20
Hi @fimaljo 👋 
Can you please provide a link to a minimal reproduction sample? Thanks!

**Comment by felangel** [comment] 2024-06-12 03:07
Closing for now since this issue is quite old and there isn't a minimal reproduction sample. If this is still a problem please file a new issue with a link to a reproduction sample, thanks!

**Closed by felangel** 2024-06-12 03:07 UTC
Labels: question, waiting for response
