### ISSUE TITLE
Throws type 'Null' is not a subtype of type 'Future<void>'

### ISSUE THREAD

**Issue by shinayser** [felangel/mocktail#45] opened 2021-05-10 23:49 UTC
I think I found a bug, mostly with the error message throw that can causes confusion:

Consider the following classes: 

```dart
class DataProvider {
  Future<void> justAFutureFunction() async {
    print('Ok, nothing wrong here');
  }
}

class JustARepository {
  final DataProvider innerRepo;

  JustARepository(this.innerRepo);

  Future<void> doSomethingWithTheRepository() async {
    await innerRepo.justAFutureFunction();
    print('Everything is ok');
  }
}
```

Now the following test that mocks the DataProvider call and everything works fine:

```dart
class MockInnerRepo extends Mock implements DataProvider {}

void main() {
  test('Test', () {
    final innerRepo = MockInnerRepo();
    final outerRepo = JustARepository(innerRepo);

    when(() => innerRepo.justAFutureFunction())
        .thenAnswer((invocation) => Future.value());

    expect(outerRepo.doSomethingWithTheRepository(), completes);
  });
}
```

Now if you add a second `when` call, that mocks the method from the repository, we get the error:
```type 'Null' is not a subtype of type 'Future<void>```:

```dart
class MockInnerRepo extends Mock implements DataProvider {}

void main() {
  test('Test', () {
    final innerRepo = MockInnerRepo();
    final outerRepo = JustARepository(innerRepo);

    when(() => innerRepo.justAFutureFunction())
        .thenAnswer((invocation) => Future.value());

    /// This code causes the test to break
    when(() => outerRepo.doSomethingWithTheRepository())
        .thenAnswer((invocation) => Future.value());

    expect(outerRepo.doSomethingWithTheRepository(), completes);
  });
}
```

I know that calling a method from something that is not being mocked sounds stupid, but this code above actually works with mockito. I spend about 2 hours trying to figure out what I was doing wrong and the error was the way I wrote thet test itself. But like I said, everything was passing with mockito.

Maybe telling the user that we should mock the Repository before trying to call `when` on it?

**Comment by felangel** [comment] 2021-05-14 20:58
Hi @shinayser 👋 
Thanks for opening an issue!

I believe the problem is you are using `when` on a "real" instance. `when` should only be called with `Mock` instances. Hope that helps 👍

**Comment by MatiSanchez** [comment] 2021-05-17 23:29
Hi!! I don't know if it's the same case (or maybe it's my error..)

But I am trying to update to _null safety_ the _ResoCoder TDD Clean Architecture Course_ using _mocktail_ and I am getting the same error..
**number_trivia_repository_impl_test.dart**

```dart
class MockNumberTriviaRemoteDataSource extends Mock implements NumberTriviaRemoteDataSource {}
class MockNumberTriviaLocalDataSource extends Mock implements NumberTriviaLocalDataSource {}
class MockNetworkInfo extends Mock implements NetworkInfo {}

void main() {
  late NumberTriviaRepositoryImpl repository;
  late MockNumberTriviaRemoteDataSource mockRemoteDataSource;
  late MockNumberTriviaLocalDataSource mockLocalDataSource;
  late MockNetworkInfo mockNetworkInfo;

  setUp(() {
    mockRemoteDataSource = MockNumberTriviaRemoteDataSource();
    mockLocalDataSource = MockNumberTriviaLocalDataSource();
    mockNetworkInfo = MockNetworkInfo();
    repository = NumberTriviaRepositoryImpl(
      remoteDataSource : mockRemoteDataSource,
      localDataSource : mockLocalDataSource,
      networkInfo : mockNetworkInfo
    );
  });

  group('getConcreteNumberTrivia', () {
    final tNumber = 1;
    final tNumberTriviaModel = NumberTriviaModel(text: 'test trivia', number: tNumber);
    final NumberTrivia tNumberTrivia = tNumberTriviaModel;

    //This fails!!
    test('should check if the device is online', () async {
      //arrange
      when(() => mockNetworkInfo.isConnected).thenAnswer((_) async => true);
      // act
      repository.getConcreteNumberTrivia(tNumber);
      // assert
      verify(() => mockNetworkInfo.isConnected);
    });
    
    //This works correctly
    group('device is online', () {
      setUp(() {
        when(() => mockNetworkInfo.isConnected).thenAnswer((_) async => true);
      });

      test('should return remote data when the call to remote data source is successful', () async {
        //arrange
        when(() => mockRemoteDataSource.getConcreteNumberTrivia(tNumber)).thenAnswer((_) async => tNumberTriviaModel);
        //act
        final result = await repository.getConcreteNumberTrivia(tNumber);
        //asert
        verify(() => mockRemoteDataSource.getConcreteNumberTrivia(tNumber));
        expect(result, Right(tNumberTrivia));
      });
    });
  });
```

Result test

```
package:clean_architecture/features/number_trivia/data/datasources/number_trivia_remote_data_source.dart 7:29  MockNumberTriviaRemoteDataSource.getConcreteNumberTrivia
package:clean_architecture/features/number_trivia/data/repositories/number_trivia_repository_impl.dart 23:41   NumberTriviaRepositoryImpl.getConcreteNumberTrivia
test\features\number_trivia\data\Repositories\number_trivia_repository_impl_test.dart 46:24                    main.<fn>.<fn>
test\features\number_trivia\data\Repositories\number_trivia_repository_impl_test.dart 42:50                    main.<fn>.<fn>

type 'Null' is not a subtype of type 'Future<NumberTriviaModel>'
```

I pass you the other classes..

**number_trivia.dart**

```dart
class NumberTrivia extends Equatable {
  final String text;
  final int number;

  NumberTrivia({
    required this.text,
    required this.number
  });

  @override
  List<Object> get props => [text, number];
}
```

**number_trivia_model.dart**

```dart
class NumberTriviaModel extends NumberTrivia  {
  NumberTriviaModel({
    required String text,
    required int number
  }) : super(text: text, number: number);

  factory NumberTriviaModel.fromJson(Map<String, dynamic> json) => NumberTriviaModel(text: json['text'], number: (json['number']).toInt());

  Map<String, dynamic> toJson() => {'text': text, 'number': number};
}
```


**number_trivia_local_data_source.dart**

```dart
abstract class NumberTriviaLocalDataSource {
  /// Gets the cached [NumberTriviaModel] which was gotten the last time
  /// the user had an internet connection.
  ///
  /// Throws [CacheException] if no cached data is present.
  Future<NumberTriviaModel> getLastNumberTrivia();
  Future<void> cacheNumberTrivia(NumberTriviaModel triviaToCache);
}
```
**number_trivia_remote_data_source.dart**

```dart
abstract class NumberTriviaRemoteDataSource {
  /// Calls the http://numbersapi.com/{number} endpoint.
  ///
  /// Throws a [ServerException] for all error codes.
  Future<NumberTriviaModel> getConcreteNumberTrivia(int number);

  /// Calls the http://numbersapi.com/random endpoint.
  ///
  /// Throws a [ServerException] for all error codes.
  Future<NumberTriviaModel> getRandomNumberTrivia();
}
```

**number_trivia_repository_impl.dart**

```dart
class NumberTriviaRepositoryImpl implements NumberTriviaRepository {
  final NumberTriviaRemoteDataSource remoteDataSource;
  final NumberTriviaLocalDataSource localDataSource;
  final NetworkInfo networkInfo;

  NumberTriviaRepositoryImpl({
    required this.remoteDataSource,
    required this.localDataSource,
    required this.networkInfo
  });

  @override
  Future<Either<Failure, NumberTrivia>> getConcreteNumberTrivia(int number) async {
    networkInfo.isConnected;
    return Right(await remoteDataSource.getConcreteNumberTrivia(number));
  }
}
```

**Comment by felangel** [comment] 2021-05-20 20:50
Hi @shinayser 👋 
Thanks for opening an issue!

The reason why you're seeing that error is because the real outerRepo call invokes `justAFutureFunction` on the mock innerRepo which is not stubbed. I'll see what I can do to try to improve the error 👍

**Comment by felangel** [comment] 2021-05-20 21:45
@MatiSanchez the following works for me:

```dart
import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';
import 'package:mocktail/mocktail.dart';
import 'package:test/test.dart';

abstract class Failure extends Equatable {
  @override
  List<Object> get props => [];
}

abstract class NetworkInfo {
  Future<bool> get isConnected;
}

class NumberTrivia extends Equatable {
  final String text;
  final int number;

  NumberTrivia({required this.text, required this.number});

  @override
  List<Object> get props => [text, number];
}

class NumberTriviaModel extends NumberTrivia {
  NumberTriviaModel({required String text, required int number})
      : super(text: text, number: number);

  factory NumberTriviaModel.fromJson(Map<String, dynamic> json) =>
      NumberTriviaModel(text: json['text'], number: (json['number']).toInt());

  Map<String, dynamic> toJson() => {'text': text, 'number': number};
}

abstract class NumberTriviaLocalDataSource {
  /// Gets the cached [NumberTriviaModel] which was gotten the last time
  /// the user had an internet connection.
  ///
  /// Throws [CacheException] if no cached data is present.
  Future<NumberTriviaModel> getLastNumberTrivia();
  Future<void> cacheNumberTrivia(NumberTriviaModel triviaToCache);
}

abstract class NumberTriviaRemoteDataSource {
  /// Calls the http://numbersapi.com/{number} endpoint.
  ///
  /// Throws a [ServerException] for all error codes.
  Future<NumberTriviaModel> getConcreteNumberTrivia(int number);

  /// Calls the http://numbersapi.com/random endpoint.
  ///
  /// Throws a [ServerException] for all error codes.
  Future<NumberTriviaModel> getRandomNumberTrivia();
}

abstract class NumberTriviaRepository {
  Future<Either<Failure, NumberTrivia>> getConcreteNumberTrivia(int number);
  Future<Either<Failure, NumberTrivia>> getRandomNumberTrivia();
}

class NumberTriviaRepositoryImpl implements NumberTriviaRepository {
  final NumberTriviaRemoteDataSource remoteDataSource;
  final NumberTriviaLocalDataSource localDataSource;
  final NetworkInfo networkInfo;

  NumberTriviaRepositoryImpl(
      {required this.remoteDataSource,
      required this.localDataSource,
      required this.networkInfo});

  @override
  Future<Either<Failure, NumberTrivia>> getConcreteNumberTrivia(
      int number) async {
    await networkInfo.isConnected;
    return Right(await remoteDataSource.getConcreteNumberTrivia(number));
  }

  @override
  Future<Either<Failure, NumberTrivia>> getRandomNumberTrivia() async {
    return Right(await remoteDataSource.getRandomNumberTrivia());
  }
}

class MockNumberTriviaRemoteDataSource extends Mock
    implements NumberTriviaRemoteDataSource {}

class MockNumberTriviaLocalDataSource extends Mock
    implements NumberTriviaLocalDataSource {}

class MockNetworkInfo extends Mock implements NetworkInfo {}

void main() {
  late NumberTriviaRepositoryImpl repository;
  late MockNumberTriviaRemoteDataSource mockRemoteDataSource;
  late MockNumberTriviaLocalDataSource mockLocalDataSource;
  late MockNetworkInfo mockNetworkInfo;

  setUp(() {
    mockRemoteDataSource = MockNumberTriviaRemoteDataSource();
    mockLocalDataSource = MockNumberTriviaLocalDataSource();
    mockNetworkInfo = MockNetworkInfo();
    repository = NumberTriviaRepositoryImpl(
        remoteDataSource: mockRemoteDataSource,
        localDataSource: mockLocalDataSource,
        networkInfo: mockNetworkInfo);
  });

  group('getConcreteNumberTrivia', () {
    final tNumber = 1;
    final tNumberTriviaModel =
        NumberTriviaModel(text: 'test trivia', number: tNumber);
    final NumberTrivia tNumberTrivia = tNumberTriviaModel;

    //This fails!!
    test('should check if the device is online', () async {
      //arrange
      when(() => mockRemoteDataSource.getConcreteNumberTrivia(any()))
          .thenAnswer((_) async => NumberTriviaModel(text: 'test', number: 42));
      when(() => mockNetworkInfo.isConnected).thenAnswer((_) async => true);
      // act
      repository.getConcreteNumberTrivia(tNumber);
      // assert
      verify(() => mockNetworkInfo.isConnected);
    });

    //This works correctly
    group('device is online', () {
      setUp(() {
        when(() => mockNetworkInfo.isConnected).thenAnswer((_) async => true);
      });

      test(
          'should return remote data when the call to remote data source is successful',
          () async {
        //arrange
        when(() => mockRemoteDataSource.getConcreteNumberTrivia(tNumber))
            .thenAnswer((_) async => tNumberTriviaModel);
        //act
        final result = await repository.getConcreteNumberTrivia(tNumber);
        //asert
        verify(() => mockRemoteDataSource.getConcreteNumberTrivia(tNumber));
        expect(result, Right(tNumberTrivia));
      });
    });
  });
}
```

**Comment by felangel** [comment] 2021-05-20 21:48
@shinayser looked into this a bit more closely and I think the error message is accurate because technically `doSomethingWithTheRepository` invokes `justAFutureFunction` on a mock instance which hasn't been stubbed. This results in the `justAFutureFunction` returning `null` when the return type should be `Future<void>` hence the error message:

`type 'Null' is not a subtype of type 'Future<void>`

Closing for now since this is working as expected in my opinion.

**Closed by felangel** 2021-05-20 21:48 UTC
Labels: investigating

**Comment by shinayser** [comment] 2021-05-20 21:52
I never said that this is not working. Mocktail is working fine!
The point of my issue is to improve the error message and prevent errors ocurring to other people. 
It tooks me lots of time to realize that this was the cause of the problem and like I said, this code works on Mockito.  So is highly probable that some other people will suffer from the same problem.

**Comment by felangel** [comment] 2021-05-21 21:46
> I never said that this is not working. Mocktail is working fine!
> The point of my issue is to improve the error message and prevent errors ocurring to other people.
> It tooks me lots of time to realize that this was the cause of the problem and like I said, this code works on Mockito. So is highly probable that some other people will suffer from the same problem.

Yeah I totally get it. The issue is this is a really specific case where you are stubbing a method on a real instance which invokes a method on a mock instance. For example if you changed your code to the following:

```dart
class DataProvider {
  Future<void> justAFutureFunction() async {
    print('Ok, nothing wrong here');
  }
}

class JustARepository {
  final DataProvider innerRepo;

  JustARepository(this.innerRepo);

  Future<void> doSomethingWithTheRepository() async {
    // Do not invoke method on a Mock instance
    // await innerRepo.justAFutureFunction();
    print('Everything is ok');
  }
}
```

Then you'll get the expected error:

`Bad state: No method stub was called from within `when()`. Was a real method called, or perhaps an extension method?`

The reason for the error you're seeing is the call to a real mock which isn't stubbed which is part of the larger call.

**Comment by MatiSanchez** [comment] 2021-05-22 12:58
> @MatiSanchez the following works for me:..

Ty @felangel! I had a feeling that I was doing something wrong..

**Comment by flutter-evangelist** [comment] 2021-05-22 14:56
@MatiSanchez Hi Mati, what was it. I'm also facing the same issue and I couldn't figure it out yet.

**Comment by MatiSanchez** [comment] 2021-05-22 15:59
> @MatiSanchez Hi, what was it. I'm also facing the same issue and I couldn't figure it out yet.

@flutter-evangelist Hi!

You need to create the stub of the methods into the mocks that you will use in your tests.

For example, I advanced with the migration of the tutorial and in the part when `NumberTriviaRepositoryImpl` use cache with `SharedPreferenes`, you need to create the stub for the `cacheNumberTrivia` method:

```dart
    test('should check if the device is online', () async {
      //arrange
      //Stub for mockRemoteDataSource.getConcreteNumberTrivia
      when(() => mockRemoteDataSource.getConcreteNumberTrivia(tNumber))
          .thenAnswer((_) async => tNumberTriviaModel);
      //Stub for mockLocalDataSource.cacheNumberTrivia
      when(() => mockLocalDataSource.cacheNumberTrivia(tNumberTriviaModel))
          .thenAnswer((_) async => Future.value());
      //Stub for mockNetworkInfo.isConnected
      when(() => mockNetworkInfo.isConnected).thenAnswer((_) async => true);
      // act
      repository.getConcreteNumberTrivia(tNumber);
      // assert
      verify(() => mockNetworkInfo.isConnected);
    });
```

Btw, I don't know if this is the correct way to handle methods that return `Future <void>` .. Maybe @felangel  can confirm this..

**Comment by flutter-evangelist** [comment] 2021-05-22 16:28
Oh okay, thanks for the explanation, I guess I'm having a different problem. For some reason, the params are not matching up, even though I give the same exact value, and the hashcode also matches. If I give any() then it works.

**Comment by MatiSanchez** [comment] 2021-05-22 17:26
@flutter-evangelist Can you provide the code please?

**Comment by basti12354** [comment] 2022-07-16 09:49
Hi,

I am having a similar issue. 

I am having a class that handles notifications (final locator = GetIt.instance):

`class WorkoutNotificationsCreatorAndRemover {
  WorkoutNotifications workoutNotificationsObject = WorkoutNotifications();
  NotificationRepository _notificationRepository = locator<NotificationRepository>();
  NotificationService _notificationService = locator<NotificationService>();

  WorkoutNotificationsCreatorAndRemover(this.workoutNotificationsObject);

  void createNotifications(List<Workout> allWorkouts) {
    for (int i = 0; i < allWorkouts.length; i++) {
      Workout workout = allWorkouts[i];
      scheduleNotification(workout);
      workoutNotificationsObject.listOfCreatedNotifications.add(workout.uniqueID);
    }
    _notificationRepository.saveToDB(workoutNotificationsObject);
  }

  void scheduleNotification(Workout workout) {
    _notificationService.showScheduledNotification(workout: workout);
  }
}`

To test this class I created the following test:

`  test('WorkoutNotifications one ITEM notifications', () {
    var notificationsRepo = MockNotificationsRepository();
    var notificationService = MockNotificationService();

    locator.registerSingleton<NotificationService>(notificationService);
    locator.registerSingleton<NotificationRepository>(notificationsRepo);

    Workout workout = TestObjects.createTestWorkoutOfTheDay();
    when(() => notificationService.showScheduledNotification(workout: workout)).thenAnswer(
            (_)  async {
          print("showScheduledNotification was called");
        }
    );
    WorkoutNotificationsCreatorAndRemover creatorAndRemover = WorkoutNotificationsCreatorAndRemover(WorkoutNotifications());
    when(() => notificationsRepo.saveToDB(creatorAndRemover.workoutNotificationsObject)).thenAnswer(
            (_)  async {
          print("saveToday was called");
          return Future<bool>.value(true);
        }
    );
    creatorAndRemover.createNotifications([TestObjects.createTestWorkoutOfTheDay()]);

    expect(creatorAndRemover.workoutNotificationsObject.listOfCreatedNotifications.length, 1);
  });`

**Issue: print("showScheduledNotification was called"); is never called**
Instead of the mock the original method in class "NotificationService" is getting called and I am getting the "type 'Null' is not a subtype of type 'Future<void>'" error.

`  Future<void> showScheduledNotification({required Workout workout}) async {
        _flutterLocalNotificationsPlugin.zonedSchedule(workout.uniqueID, workout.workoutName, "You have scheduled a workout today!", tz.TZDateTime.from(workout.dateOfCreation, tz.local), await _notificationDetails(),
      payload: "sarah.abs", androidAllowWhileIdle: true, uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime, );
  }` 


If I am using the debugger and checking my creatorAndRemover class then I can see that this instance is using my mock objects.

![image](https://user-images.githubusercontent.com/10846809/179349756-b5c5ac01-a68d-4c21-9654-7a5332aeac77.png)

What is wrong with my code? Didn't get it...

**Comment by gaurishankar007** [comment] 2022-11-08 06:10
This is a problem with the null safety.

**Comment by esperaking81** [comment] 2024-04-08 10:05
I was having this exact same issue.
My solution was stubbing the call to the innerRepo in the setUp() function inside the main test function block.
