### ISSUE TITLE
Incompatible with Flutter 3.10

### ISSUE THREAD

**Issue by boldt** [felangel/mocktail#197] opened 2023-05-25 09:14 UTC
**Describe the bug**

mocktail 0.3.0 is incompatible with flutter 3.10:

```
And because app depends on integration_test from sdk, build_runner >=2.0.2 <2.3.1 is incompatible with mocktail 0.3.0.
So, because app depends on both build_runner 2.3.0 and mocktail 0.3.0, version solving failed.
```

**Comment by felangel** [comment] 2023-05-25 13:17
Hi @boldt 👋
Can you please share the pubspec.yaml? Thanks!

**Comment by richaux** [comment] 2023-08-02 07:41
In case it helps, I've been using `mocktail 0.3.0` (and `1.0.0` too) with `flutter 3.10` and don't get incompatibility messages: I also have `build_runner 2.4.6`, so an upgrade of that may resolve.  🤞

**Comment by felangel** [comment] 2023-08-02 14:44
Closing this for now since there are no actionable next steps. Feel free to provide more info/reproduction if it’s still an issue and I’m happy to take a closer look 👍

**Closed by felangel** 2023-08-02 14:44 UTC
Labels: question, waiting for response
