### ISSUE TITLE
Cant use mocktail ^0.3.0 with freezed ^2.3.2

### ISSUE THREAD

**Issue by jtdLab** [felangel/mocktail#177] opened 2023-01-15 21:45 UTC
**Describe the bug**
Version solving fails with mocktail ^0.3.0 and freezed ^2.3.2

**Comment by felangel** [comment] 2023-01-15 21:57
Hi @jtdLab 👋
This is a duplicate of https://github.com/felangel/mocktail/issues/164

**Closed** 2023-01-17 18:34 UTC
Labels: duplicate
