### ISSUE TITLE
Issue with mocking where method in Firestore query.

### ISSUE THREAD

**Issue by Dan-Y-Ko** [felangel/mocktail#141] opened 2022-07-26 04:48 UTC
Hello,
I am getting the classic "Error type 'Null' is not a subtype of type 'Query<Map<String, dynamic>>'" error but I have stubbed the method and I am still getting this error.

Here's screenshot of the error: [https://imgur.com/a/Zqhu2oe](url)

Actual code:

```
Future<void> _createUser(String? id) async {
    final QuerySnapshot result =
        await _db.collection('Users').where('id', isEqualTo: id).get();

    if (result.docs.isEmpty) {
      await _db.collection("Users").add({
        "id": id,
      });
    }
  }
```

Test code:

```
class MockFireStore extends Mock implements FirebaseFirestore {}
class MockCollectionReference extends Mock
    implements CollectionReference<Map<String, dynamic>> {}

class MockQuery extends Mock implements Query<Map<String, dynamic>> {}

class MockQuerySnapshot extends Mock
    implements QuerySnapshot<Map<String, dynamic>> {}

class MockDocumentReference extends Mock
    implements DocumentReference<Map<String, dynamic>> {}

void main() {
   late FirebaseFirestore instance;
   late CollectionReference<Map<String, dynamic>> mockCollectionReference;
   late Query<Map<String, dynamic>> mockQuery;
   late QuerySnapshot<Map<String, dynamic>> mockQuerySnapshot;
   late DocumentReference<Map<String, dynamic>> mockDocumentReference;
   
   setUp(() {
      instance = MockFireStore();
      mockCollectionReference = MockCollectionReference();
      mockQuery = MockQuery();
      mockQuerySnapshot = MockQuerySnapshot();
      mockDocumentReference = MockDocumentReference();
   });

   test('', () async {
      when(() => instance.collection(any()))
          .thenReturn(mockCollectionReference);

      when(() => mockCollectionReference.where(any())).thenReturn(mockQuery);

      when(() => mockQuery.get()).thenAnswer(
        (_) async => mockQuerySnapshot,
      );

      when(() => mockCollectionReference.add(any()))
          .thenAnswer((_) async => mockDocumentReference);
   });
}
```

I decided to play around with the query and did a direct query on the document instead of querying on the collection with the where and I was able to get the tests passing, so I believe the issue is the where query method, but I'm not sure what the actual issue is.

**Comment by felangel** [comment] 2024-04-20 03:49
Hi @Dan-Y-Ko 👋 
I'm going to close this for now since the issue is quite old but if this is still an issue, please let me know and ideally share a minimal reproduction sample and I'm happy to take a closer look, thanks!

**Closed by felangel** 2024-04-20 03:49 UTC

**Comment by safield** [comment] 2025-01-28 06:07
Anyone know how to solve this? This repo is riddled with issues of this exact type, with not answers.

@felangel Do you have any idea what is going on here? I have a similar problem with mocking Firestore.

**Comment by felangel** [comment] 2025-01-28 06:56
> Anyone know how to solve this? This repo is riddled with issues of this exact type, with not answers.
> 
> [@felangel](https://github.com/felangel) Do you have any idea what is going on here? I have a similar problem with mocking Firestore.

Can you share your specific test and I’m happy to take a closer look and provide a fix 👍

**Comment by iveloff-developer** [comment] 2025-02-20 17:20
@felangel, I have a case similar to discussion, maybe you could help me with it... I'll open to any suggestions, tips to make it better way and open to any improvement for existing code and tests. 


Code to test:
 ```dart
 final class FirebaseUserDatabaseService implements UserDatabaseService {
  FirebaseUserDatabaseService({required final FirebaseFirestore firestore})
    : _firestore = firestore;

  final FirebaseFirestore _firestore;

  // TODO(iveloff-developer): cover with unit tests.
  @override
  Stream<bool> userExistsStream({required final String uid}) => _firestore
      .collection(collectionName)
      .doc(uid)
      .snapshots()
      .distinct()
      .map((final snapshot) => snapshot.exists)
      // Handle all errors by returning false.
      // TODO(iveloff-developer): separate error handling for different errors.
      .handleError((final _) => false);
```

Tests:
```dart
import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

final class MockFirebaseFirestore extends Mock implements FirebaseFirestore {}

final class MockCollectionReference extends Mock
    implements CollectionReference<Map<String, dynamic>> {}

final class MockDocumentReference extends Mock
    implements DocumentReference<Map<String, dynamic>> {}

final class MockDocumentSnapshot extends Mock
    implements DocumentSnapshot<Map<String, dynamic>> {}

void main() {
  group('userExistsStream', () {
    const mockUid = 'mock-uid';
    const collectionName = 'users';

    late FirebaseFirestore mockFirestore;
    late FirebaseUserDatabaseService userDatabaseService;

    setUp(() {
      mockFirestore = MockFirebaseFirestore();

      userDatabaseService = FirebaseUserDatabaseService(
        firestore: mockFirestore,
      );
    });

    test('access existing snaphots.', () {
      final collection = MockCollectionReference();
      final doc = MockDocumentReference();

      when(
        () => mockFirestore.collection(collectionName),
      ).thenReturn(collection);
      when(() => collection.doc(mockUid)).thenReturn(doc);
      when(
        doc.snapshots,
      ).thenAnswer((_) => Stream.value(MockDocumentSnapshot()));

      userDatabaseService.userExistsStream(uid: mockUid);

      verifyInOrder([
        () => mockFirestore.collection(collectionName),
        () => collection.doc(mockUid),
        doc.snapshots,
      ]);
    });

    test('emits [true] when snapshot exists.', () {
      final collection = MockCollectionReference();
      final doc = MockDocumentReference();
      final snapshot = MockDocumentSnapshot();

      when(
        () => mockFirestore.collection(collectionName),
      ).thenReturn(collection);
      when(() => collection.doc(mockUid)).thenReturn(doc);
      when(() => snapshot.exists).thenReturn(true);
      when(doc.snapshots).thenAnswer((_) => Stream.value(snapshot).distinct());

      expect(userDatabaseService.userExistsStream(uid: mockUid), emits(true));
    });

    test("emits [false] when snapshot doesn't exists.", () {
      final collection = MockCollectionReference();
      final doc = MockDocumentReference();
      final snapshot = MockDocumentSnapshot();

      when(
        () => mockFirestore.collection(collectionName),
      ).thenReturn(collection);
      when(() => collection.doc(mockUid)).thenReturn(doc);
      when(() => snapshot.exists).thenReturn(false);
      when(doc.snapshots).thenAnswer((_) => Stream.value(snapshot).distinct());

      expect(userDatabaseService.userExistsStream(uid: mockUid), emits(false));
    });

    test("emits [false] when any error occurs.", () {
      final collection = MockCollectionReference();
      final doc = MockDocumentReference();

      when(
        () => mockFirestore.collection(collectionName),
      ).thenReturn(collection);
      when(() => collection.doc(mockUid)).thenReturn(doc);
      when(doc.snapshots).thenAnswer((_) => Stream.error(Exception()));

      expect(userDatabaseService.userExistsStream(uid: mockUid), emits(false));
    });

    test('snapshots should be distinct.', () async {
      final collection = MockCollectionReference();
      final doc = MockDocumentReference();
      final snapshotExists = MockDocumentSnapshot();
      final snapshotNotExists = MockDocumentSnapshot();

      when(
        () => mockFirestore.collection(collectionName),
      ).thenReturn(collection);
      when(() => collection.doc(mockUid)).thenReturn(doc);
      when(() => snapshotExists.exists).thenReturn(true);
      when(() => snapshotNotExists.exists).thenReturn(false);
      when(doc.snapshots).thenAnswer(
        (_) =>
            Stream.fromIterable([
              snapshotNotExists,
              snapshotExists,
              snapshotExists,
            ]).distinct(),
      );

      expect(
        userDatabaseService.userExistsStream(uid: mockUid),
        emitsInOrder([false, true]),
      );
    });
  });
}
```

One test fails with next results:

> Expected: should emit an event that <false>
  Actual: <Instance of '_HandleErrorStream<bool>'>
   Which: emitted x Stream closed.
package:matcher                                                          expect
test/data/services/user_database/firebase/implementation_test.dart 99:7  main.<fn>.<fn>

**Comment by felangel** [comment] 2025-02-20 18:23
@iveloff-developer I believe the issue is not in the test but rather your implementation. If you want to transform errors you need to use the `.transform` API like so:

```dart
  @override
  Stream<bool> userExistsStream({required final String uid}) => _firestore
      .collection('users')
      .doc(uid)
      .snapshots()
      .distinct()
      .map((final snapshot) => snapshot.exists)
      // Handle all errors by returning false.
      // TODO(iveloff-developer): separate error handling for different errors.
      .transform(
        StreamTransformer.fromHandlers(
          handleData: (data, sink) => sink.add(data),
          handleError: (error, stackTrace, sink) => sink.add(false),
          handleDone: (sink) => sink.close(),
        ),
      );
```

Then your existing test should pass. Hope that helps 👍

**Comment by iveloff-developer** [comment] 2025-02-21 11:02
@felangel, that's excectly what I need. Now I can manipulate with errors easily, thank you!
