### ISSUE TITLE
Invalid argument(s): The "any" argument matcher is used outside of method stubbing (via when) or verification (via verify or untilCalled). This is invalid, and results in bad behavior during the next stubbing or verification.

### ISSUE THREAD

**Issue by raxahai** [felangel/mocktail#163] opened 2022-11-05 10:45 UTC
```
class FakeRequest extends Fake implements RequestOptions{}

setUp((){
registerCallback(FakeRequest())
});

test("should fetch customer info", () async {
    // arrange
    when(() => mockDioClient.get(any())).thenAnswer(
      (_) async => Response(
        data: fixture("customer_fixture.json"),
        requestOptions: any(),
        statusCode: 200,
      ),
    );

    // act
    var result = await profileRemoteDataSourceImpl.getCustomerInfo();

    // assert
    expect(result, testCustomerModel);
    verify(() => mockDioClient.get(Urls.getCustomerInfo));
    verifyNoMoreInteractions(mockDioClient);
  });
```

**Comment by felangel** [comment] 2024-04-20 03:42
Hi @raxahai 👋 
Thanks for opening an issue! If you're still having trouble with this can you please share a link to a minimal reproduction sample? It's much easier for me to help if I'm able to reproduce the issue locally, thanks!

**Comment by felangel** [comment] 2024-06-12 03:09
Closing for now since this issue is quite old and there isn't a minimal reproduction sample. If this is still a problem please file a new issue with a link to a reproduction sample, thanks!

**Closed by felangel** 2024-06-12 03:09 UTC
Labels: question, waiting for response
