### ISSUE TITLE
bloc_test^9.1.0 version solving failed with build_runner ^2.3.2 

### ISSUE THREAD

**Issue by SuhwanCha** [felangel/mocktail#169] opened 2022-12-01 02:49 UTC
Hello, I'm using `build_runner^2.3.2` and `flutter_bloc^8.1.1` and cannot install `bloc_test^9.1.0`

**pubspec.yaml**
```yaml
name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  # bloc_test: ^9.1.0 <- not working!

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
```

**Error log**
```
    Because build_runner >=2.3.1 depends on frontend_server_client ^3.0.0 and test_core >=0.3.23 <0.4.17 depends on frontend_server_client ^2.1.0, build_runner >=2.3.1 is incompatible with test_core >=0.3.23 <0.4.17.
    And because test >=1.21.4 <1.21.5 depends on test_core 0.4.16 and test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0, if build_runner >=2.3.1 and test >=1.17.10 <1.20.0-∞ or >=1.21.4 <1.21.5-∞ then analyzer >=1.0.0 <3.0.0.
    And because test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0 and build_runner >=2.2.1 depends on analyzer >=4.4.0 <6.0.0, build_runner >=2.3.1 is incompatible with test >=1.16.6 <1.20.0-∞ or >=1.21.4 <1.21.5-∞.
(1) So, because test >=1.21.3 <1.21.4 depends on test_api 0.4.11 and test >=1.21.2 <1.21.3 depends on test_api 0.4.10, if build_runner >=2.3.1 and test >=1.16.6 <1.20.0-∞ or >=1.21.2 <1.21.5-∞ then test_api 0.4.10 or 0.4.11.

    Because test >=1.22.0 depends on test_api 0.4.16 and test >=1.21.7 <1.22.0 depends on test_api 0.4.15, test >=1.21.7 requires test_api 0.4.15 or 0.4.16.
    And because test >=1.21.6 <1.21.7 depends on test_api 0.4.14 and test >=1.21.5 <1.21.6 depends on test_api 0.4.13, test >=1.21.5 requires test_api 0.4.13 or 0.4.14 or 0.4.15 or 0.4.16.
    And because test >=1.20.0 <1.21.2 depends on test_api 0.4.9 and test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19, test >=1.16.0-nullsafety.19 <1.16.6-∞ or >=1.20.0 <1.21.2-∞ or >=1.21.5 requires test_api 0.2.19 or 0.4.9 or 0.4.13 or 0.4.14 or 0.4.15 or 0.4.16.
    And because if build_runner >=2.3.1 and test >=1.16.6 <1.20.0-∞ or >=1.21.2 <1.21.5-∞ then test_api 0.4.10 or 0.4.11 (1), if build_runner >=2.3.1 and test >=1.16.0-nullsafety.19 then test_api 0.2.19 or 0.4.9 or 0.4.10 or 0.4.11 or 0.4.13 or 0.4.14 or 0.4.15 or 0.4.16.
    And because every version of flutter_test from sdk depends on test_api 0.4.12, one of build_runner >=2.3.1 or test >=1.16.0-nullsafety.19 or flutter_test from sdk must be false.
    And because bloc_test >=8.0.0-nullsafety.5 depends on test ^1.16.0 and bloc_test >=7.0.0 <8.0.0-nullsafety.0 depends on bloc ^6.0.0, if build_runner >=2.3.1 and flutter_test from sdk and bloc_test >=7.0.0 <8.0.0-nullsafety.0 or >=8.0.0-nullsafety.5 then bloc ^6.0.0.
    And because bloc_test >=6.0.1 <7.0.0-dev.1 depends on bloc ^5.0.1 and bloc_test >=6.0.0 <6.0.1 depends on bloc ^5.0.0, if build_runner >=2.3.1 and flutter_test from sdk and bloc_test >=6.0.0 <7.0.0-dev.1 or >=7.0.0 <8.0.0-nullsafety.0 or >=8.0.0-nullsafety.5 then bloc >=5.0.0 <6.0.0 or ^6.0.0.
    And because bloc_test >=5.0.0 <6.0.0-dev.1 depends on bloc ^4.0.0 and bloc_test >=3.0.0 <5.0.0-dev.1 depends on bloc ^3.0.0, if build_runner >=2.3.1 and flutter_test from sdk and bloc_test >=3.0.0 <5.0.0-dev.1 or >=5.0.0 <6.0.0-dev.1 or >=6.0.0 <7.0.0-dev.1 or >=7.0.0 <8.0.0-nullsafety.0 or >=8.0.0-nullsafety.5 then bloc ^3.0.0 or ^4.0.0 or >=5.0.0 <6.0.0 or ^6.0.0.
    And because bloc_test >=2.0.0 <3.0.0-dev.1 depends on bloc ^2.0.0 and bloc_test ^1.0.0 depends on bloc ^1.0.0, if build_runner >=2.3.1 and flutter_test from sdk and bloc_test >=1.0.0 <3.0.0-dev.1 or >=3.0.0 <5.0.0-dev.1 or >=5.0.0 <6.0.0-dev.1 or >=6.0.0 <7.0.0-dev.1 or >=7.0.0 <8.0.0-nullsafety.0 or >=8.0.0-nullsafety.5 then bloc ^1.0.0 or ^2.0.0 or ^3.0.0 or ^4.0.0 or >=5.0.0 <6.0.0 or ^6.0.0.
    And because bloc_test <1.0.0 depends on bloc ^0.16.0 and bloc_test >=8.0.0-nullsafety.1 <8.0.0-nullsafety.6 depends on bloc >=7.0.0-nullsafety.3 <7.0.0, if build_runner >=2.3.1 and flutter_test from sdk and bloc_test <3.0.0-dev.1 or >=3.0.0 <5.0.0-dev.1 or >=5.0.0 <6.0.0-dev.1 or >=6.0.0 <7.0.0-dev.1 or >=7.0.0 <8.0.0-nullsafety.0 or >=8.0.0-nullsafety.1 then bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or ^3.0.0 or ^4.0.0 or >=5.0.0 <6.0.0 or ^6.0.0 or >=7.0.0-nullsafety.3 <7.0.0.
    And because bloc_test >=8.0.0-nullsafety.0 <8.0.0-nullsafety.1 depends on bloc >=7.0.0-nullsafety.2 <7.0.0 and bloc_test >=7.0.0-dev.1 <7.0.0 depends on bloc ^6.0.0-dev.1, if build_runner >=2.3.1 and flutter_test from sdk and bloc_test <3.0.0-dev.1 or >=3.0.0 <5.0.0-dev.1 or >=5.0.0 <6.0.0-dev.1 or >=6.0.0 then bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or ^3.0.0 or ^4.0.0 or >=5.0.0 <6.0.0 or >=6.0.0-dev.1 <7.0.0 or >=7.0.0-nullsafety.2 <7.0.0.
    And because bloc_test >=6.0.0-dev.4 <6.0.0 depends on bloc ^5.0.0-dev.11 and bloc_test >=6.0.0-dev.3 <6.0.0-dev.4 depends on bloc ^5.0.0-dev.10, if build_runner >=2.3.1 and flutter_test from sdk and bloc_test <3.0.0-dev.1 or >=3.0.0 <5.0.0-dev.1 or >=5.0.0 <6.0.0-dev.1 or >=6.0.0-dev.3 then bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or ^3.0.0 or ^4.0.0 or >=5.0.0-dev.10 <6.0.0 or >=6.0.0-dev.1 <7.0.0 or >=7.0.0-nullsafety.2 <7.0.0.
    And because bloc_test >=6.0.0-dev.2 <6.0.0-dev.3 depends on bloc ^5.0.0-dev.7 and bloc_test >=6.0.0-dev.1 <6.0.0-dev.2 depends on bloc ^5.0.0-dev.6, if build_runner >=2.3.1 and flutter_test from sdk and bloc_test <3.0.0-dev.1 or >=3.0.0 <5.0.0-dev.1 or >=5.0.0 then bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or ^3.0.0 or ^4.0.0 or >=5.0.0-dev.6 <6.0.0 or >=6.0.0-dev.1 <7.0.0 or >=7.0.0-nullsafety.2 <7.0.0.
    And because bloc_test >=5.0.0-dev.4 <5.0.0 depends on bloc ^4.0.0-dev.4 and bloc_test >=5.0.0-dev.3 <5.0.0-dev.4 depends on bloc ^4.0.0-dev.3, if build_runner >=2.3.1 and flutter_test from sdk and bloc_test <3.0.0-dev.1 or >=3.0.0 <5.0.0-dev.1 or >=5.0.0-dev.3 then bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or ^3.0.0 or >=4.0.0-dev.3 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or >=6.0.0-dev.1 <7.0.0 or >=7.0.0-nullsafety.2 <7.0.0.
    And because bloc_test >=5.0.0-dev.2 <5.0.0-dev.3 depends on bloc ^4.0.0-dev.2 and bloc_test >=5.0.0-dev.1 <5.0.0-dev.2 depends on bloc ^4.0.0-dev.1, if build_runner >=2.3.1 and flutter_test from sdk and bloc_test <3.0.0-dev.1 or >=3.0.0 then bloc ^0.16.0 or ^1.0.0 or ^2.0.0 or ^3.0.0 or >=4.0.0-dev.1 <5.0.0 or >=5.0.0-dev.6 <6.0.0 or >=6.0.0-dev.1 <7.0.0 or >=7.0.0-nullsafety.2 <7.0.0.
    And because bloc_test >=3.0.0-dev.1 <3.0.0 depends on bloc ^3.0.0-dev.1 and flutter_bloc >=8.1.0 depends on bloc ^8.1.0, one of build_runner >=2.3.1 or flutter_test from sdk or bloc_test any or flutter_bloc >=8.1.0 must be false.
    And because example depends on both flutter_bloc ^8.1.1 and bloc_test any, build_runner >=2.3.1 is incompatible with flutter_test from sdk.
    So, because example depends on both flutter_test from sdk and build_runner ^2.3.2, version solving failed.
```

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm, locale en-KR)
    • Flutter version 3.3.8 on channel stable at /Users/suhwancha/development/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (3 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
```

**Comment by felangel** [comment] 2022-12-01 02:51
Hi @SuhwanCha 👋
This is a duplicate of https://github.com/felangel/mocktail/issues/164

**Closed by felangel** 2022-12-01 02:51 UTC

**Comment by SuhwanCha** [comment] 2022-12-02 01:55
> Hi @SuhwanCha 👋 This is a duplicate of #164

Sorry that I haven't check duplication!
It works well in flutter master channel
