### ISSUE TITLE
type 'Null' is not a subtype of type 'Future<LoginResponse>'

### ISSUE THREAD

**Issue by rddewan** [felangel/mocktail#157] opened 2022-10-12 01:10 UTC
**Describe the bug**
I am trying to write a test for a method that calls another method that returns a value, but the stub is never called

Repository Class
```
class LoginRepositoryImpl extends LoginRepository {
  final LoginApiService _loginApiService;
  final SecureStorage _secureStorage;
  final BaseRepository _baseRepository;


  LoginRepositoryImpl(this._loginApiService, this._secureStorage, this._baseRepository);


  @override
  Future<LoginResponse> login(LoginRequest request) {

    return _baseRepository.call<LoginResponse>(() => _loginApiService.login(request));

  }

}
```

Base Repository
```
class BaseRepository {

  Future<T> call<T>(FutureOr<T> Function() call) async  {
    try {

      return await call();

    } on DioError catch (e){

      if (e.error is SocketException) {
        throw Failure(message: e.message);
      }

      if (e.response?.statusCode == serverErrorCode) {
        throw Failure(
          message: 'Server has some issue, please try again',
          code: e.response?.statusCode,
        );
      }
      
      throw Failure(
          message: e.response?.statusMessage ?? 'Something went wrong',
          code: e.response?.statusCode,
          exception: e,
      );
    }
  }

}

```
Test
```
class MockLoginApiService extends Mock implements LoginApiService {}
class MockSecureStorage extends Mock implements SecureStorage {}
class MockBaseRepository extends Mock implements BaseRepository {}


void main() {
  late LoginApiService _mockLoginApiService;
  late SecureStorage _mockSecureStorage;
  late BaseRepository _mockBaseRepository;
  


  setUp(() {
    _mockLoginApiService = MockLoginApiService();
    _mockSecureStorage = MockSecureStorage();
    _mockBaseRepository = MockBaseRepository();
   
  });

  test('Given LoginRepository When login Then return loginResponseSuccess', () async {
    
     final _repository = LoginRepositoryImpl(
        _mockLoginApiService,
        _mockSecureStorage,
        _mockBaseRepository,
      );
    

    when(() => _mockLoginApiService.login(loginRequest))
      .thenAnswer((_) async => loginResponseSuccess);

    when(() => _mockBaseRepository.call(()  =>  _mockLoginApiService.login(loginRequest)))
      .thenAnswer((invocation) async => loginResponseSuccess);

   final result = await _repository.login(loginRequest);
    print(result);  
    
  });

```

**Expected behavior**
It should call the stub

**Logs **
```
type 'Null' is not a subtype of type 'Future<LoginResponse>'
MockBaseRepository.call
package:swap_recycling/base/base_repository.dart:17
LoginRepositoryImpl.login
package:swap_recycling/…/login/login_repository_impl.dart:34
main.<fn>
test/…/login/login_repository_impl_test.dart:51
2

✖ Given LoginRepository When login Then return loginResponseSuccess
Exited (1)
```

Paste the output of running `flutter doctor -v` here.
```
richard@MAQEs-MacBook-Pro swap_recycling_mobile % fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-TH)
    • Flutter version 3.3.4 on channel stable at /Users/richard/fvm/versions/3.3.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (7 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/richard/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 106.0.5249.119
    ! Error: Richard’s iPhone has recently restarted. Xcode will continue when Richard’s iPhone is unlocked. (code -14)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by LeonardoRosaa** [comment] 2022-10-12 19:12
Can you try something like that?

```dart
when(() => _mockBaseRepository.call(()  => any<Future<LoginResponse> Function()>()))
      .thenAnswer((invocation) async => loginResponseSuccess);
```

**Comment by lukaszdebowski** [comment] 2022-10-31 21:31
You don't need to mock the `BaseRepository`. Mocking the `LoginApiService` should be enough to make you test work.

**Comment by rddewan** [comment] 2022-11-01 03:53
I could not pass the test , I changed my `BaseRepository` to a mixin and switch to mokito it works but does not pass with mocktail

**Comment by felangel** [comment] 2022-11-16 16:26
@rddewan can you provide a link to a minimal reproduction sample?

**Comment by saschaernst** [comment] 2022-12-12 17:04
@felangel I think right now the described way of mocking async methods simply doesn't work. I copied the the provided code in the readme (and added the missing async keyword in the sleep method) but the compiler complains: The argument type 'Future<Null> Function(Invocation)' can't be assigned to the parameter type 'Future<void> Function() Function(Invocation)'.
It sounds like there is one level of function invocation to many.

**Comment by felangel** [comment] 2023-01-20 19:31
Closing for now since there is no link to a minimal reproduction sample. Feel free to provide one and I'm happy to take a closer look 👍

**Closed by felangel** 2023-01-20 19:31 UTC
Labels: question, waiting for response
