### ISSUE TITLE
Incompatible issue

### ISSUE THREAD

**Issue by mdikcinar** [felangel/mocktail#175] opened 2023-01-11 20:30 UTC
Hi, i am having issue when i try to use moctail with some other packages.

```Because test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.0-nullsafety.19 <1.17.10 requires test_api 0.2.19 or analyzer ^1.0.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0, test >=1.16.0-nullsafety.19 <1.20.0 requires test_api 0.2.19 or analyzer >=1.0.0 <3.0.0.
And because test >=1.20.0 <1.21.2 depends on test_api 0.4.9 and test >=1.21.0 <1.21.6 depends on analyzer >=2.0.0 <5.0.0, test >=1.16.0-nullsafety.19 <1.21.6 requires test_api 0.2.19 or 0.4.9 or analyzer >=1.0.0 <5.0.0.
And because test >=1.21.6 <1.21.7 depends on test_api 0.4.14 and test >=1.21.7 <1.22.0 depends on test_api 0.4.15, test >=1.16.0-nullsafety.19 <1.22.0 requires test_api 0.2.19 or 0.4.9 or 0.4.14 or 0.4.15 or analyzer >=1.0.0 <5.0.0.
And because test >=1.22.0 <1.22.1 depends on test_api 0.4.16 and test >=1.22.1 depends on test_api 0.4.17, test >=1.16.0-nullsafety.19 requires test_api 0.2.19 or 0.4.9 or 0.4.14 or 0.4.15 or 0.4.16 or 0.4.17 or analyzer >=1.0.0 <5.0.0.
And because every version of flutter_test from sdk depends on test_api 0.4.12 and mocktail >=0.1.3 depends on test ^1.16.0, if flutter_test from sdk and mocktail >=0.1.3 then analyzer >=1.0.0 <5.0.0.
And because workoutplanner depends on dart_code_metrics 5.4.0 which depends on analyzer >=5.1.0 <5.4.0, flutter_test from sdk is incompatible with mocktail >=0.1.3.
So, because workoutplanner depends on both flutter_test from sdk and mocktail 0.3.0, version solving failed.
pub get failed (1; So, because workoutplanner depends on both flutter_test from sdk and mocktail 0.3.0, version solving failed.)
```

It happens when i try to use  moctail 0.3.0 with dart_code_metrics 5.4.0 or build_runner: 2.3.3 or envied_generator: 0.3.0

How can i resolve this?

**Comment by felangel** [comment] 2023-01-11 20:40
Hi @mdikcinar 👋 
This is a duplicate of https://github.com/felangel/mocktail/issues/164

**Closed** 2023-01-11 20:46 UTC
Labels: duplicate
