### ISSUE TITLE
feat: support mocking network images for NetworkImage

### ISSUE THREAD

**Issue by danallen88** [felangel/mocktail#191] opened 2023-02-20 21:55 UTC
**Is your feature request related to a problem? Please describe.**
I have tests that exercise widgets that use `NetworkImage` instead of `Image.network`. However, using https://github.com/felangel/mocktail/tree/main/packages/mocktail_image_network does not seem to support this use case, even though `Image.network` is a wrapper around `NetworkImage`. 

**Describe the solution you'd like**
I would like to be able to use the mocktail image network library to mock network interactions initiated by `NetworkImage` in my widgets under test.

**Describe alternatives you've considered**
I've looked at this package as well: https://pub.dev/packages/network_image_mock but the behavior appears to be the same.

**Comment by danallen88** [comment] 2023-02-20 22:07
I'm just now seeing that if the test is run in isolation, it works fine, but if it is run as part of a suite of tests, it fails, which has me wondering if there is some kind of dependency between tests?

**Comment by danallen88** [comment] 2023-02-21 13:50
Some additional findings here - if I wrap all of my tests in the same file with this, then they all pass when run as a group. It seems like this is more related to https://github.com/felangel/mocktail/issues/134, so feel free to close this as a duplicate if that's the case.

**Comment by felangel** [comment] 2023-04-22 04:44
Closing as a duplicate of #134

**Closed by felangel** 2023-04-22 04:44 UTC
