### ISSUE TITLE
Not sure how to verify a void method was called

### ISSUE THREAD

**Issue by svarlet** [felangel/mocktail#10] opened 2021-01-26 11:38 UTC
**Describe the bug**
Given 2 classes A and B, when A uses a void method of B, we can't verify that this call happens.

**To Reproduce**
Full example in one simple file: https://gist.github.com/svarlet/337c0d3234cc3ba67c7d96adf788c092
Run the test, the output shows an error:

```
NoSuchMethodError: Class 'DemoDouble' has no instance method 'doSomething' with matching arguments.
Receiver: Instance of 'DemoDouble'
Tried calling: doSomething(1)
Found: doSomething(int) => void
```

**Expected behavior**
I appreciate that the method is not stubbed, thus Mocktail is correctly reporting it to me. However, the following doesn't solve the problem:

```
when(_demo).calls(#doSomething);
```

but this one does:

```
when(_demo).calls(#doSomething).thenReturn(1);
```

Yet, this is a void function, so it feels wrong. Is there another way? What am I missing?

**Comment by felangel** [comment] 2021-01-26 22:05
Hi @svarlet 👋 
Thanks for opening an issue!

You should be able to do:

```dart
when(_demo).calls(#doSomething).thenReturn(null);
```

Let me know if that helps 👍

**Comment by svarlet** [comment] 2021-01-27 11:40
Thanks for your prompt answer.
Let's appreciate that we have a workaround! However, I only found it by candidly trying `.thenReturn(1)`. I suppose, this could be documented on the project's main page to help others until a solution is found?

Speaking of solutions, this behaviour is hard-to-discover, and error prone: over time, a void method can change to a method returning a different type, leading to tests suddenly failing (returning a default X was fine, not this X is accidentally a good or bad value). Perhaps a more appropriate behaviour would be that void methods have a "do nothing" default implementation provided by `extends Mock` ?

**Comment by svarlet** [comment] 2021-02-03 10:56
Hi there,
I saw the changelog for 0.0.1-dev.10, it advertises that we can now use `.thenReturn()`. Yet, after upgrading my dependency, and replacing a `.thenReturn(1)` by `.thenReturn()`, this does not compile: 

``` 1 positional argument expected but 0 found.```

**Comment by felangel** [comment] 2021-02-04 17:04
@svarlet it should be available. Can you share a complete reproduction sample? For reference you can see the tests https://github.com/felangel/mocktail/blob/37898ba3d45810c1c849cbb4217b4fbd2c550eeb/test/mocktail_test.dart#L482

**Comment by felangel** [comment] 2021-02-08 06:04
Closing for now since but if you feel this is still an issue feel free to provide a reproduction sample and I’m happy to take a closer look 👍

**Closed by felangel** 2021-02-08 06:04 UTC
Labels: question

**Comment by svarlet** [comment] 2021-02-08 18:01
Hi! 
Apologies for the late reply.
Here is an example with the following function:
```dart
class ManagedQueries {
  void register(Uri uri) {
    //some code
  }
}
```
which I stub like this:
```dart
class ManagedQueriesDouble extends Mock implements ManagedQueries {}
```
and
```dart
managedQueries = ManagedQueriesDouble();
when(managedQueries).calls(#register).thenReturn();
```

which causes the following error on `.thenReturn()`
```
1 positional argument(s) expected, but 0 found.
Try adding the missing arguments.
```

Perhaps I should report that I'm on the flutter beta channel, and writing null safe code?

**Comment by felangel** [comment] 2021-02-08 18:13
@svarlet no worries! Are you sure you're using the latest version of mocktail? You might want to wipe your pub-cache just to be sure 👍

**Comment by svarlet** [comment] 2021-02-09 12:57
Hi @felangel , you were right, somehow I didn't have the latest version. I can now confirm that it works as expected!
Thanks

**Comment by svarlet** [comment] 2021-03-08 12:00
Hi @felangel , is this behaviour maintained in the latest (aka type safe) version of mocktail?
Right now I see this method signature:

```
void thenReturn(void expected)
```

Thus, there's a problem showing up asking to be resolved by providing a value.

**Comment by felangel** [comment] 2021-03-08 14:34
> Hi @felangel , is this behaviour maintained in the latest (aka type safe) version of mocktail?
> Right now I see this method signature:
> 
> ```
> void thenReturn(void expected)
> ```
> 
> Thus, there's a problem showing up asking to be resolved by providing a value.

In the latest version you need to pass null but I can change back to the previous behavior. My goal with the latest version was to stay as close to the mockito api as possible with hopes that mocktail could be merged into mockito.

**Comment by svarlet** [comment] 2021-03-08 18:18
Ok, thanks for explaining your intent. If your goal is to merge into mockito instead of maintaining a separate project, I can live with the obligation to return null when stubbing a void function.

**Comment by felangel** [comment] 2021-03-08 18:57
@svarlet no problem! You can follow the [discussion to merge mocktail into mockito](https://github.com/dart-lang/mockito/issues/347) and based on the outcome we can re-evaluate if it makes sense to customize the API.
