### ISSUE TITLE
Invalid argument(s): An argument matcher (like `any()`) was either not used

### ISSUE THREAD

**Issue by raxahai** [felangel/mocktail#104] opened 2021-12-29 13:32 UTC
Getting error:

Invalid argument(s): An argument matcher (like `any()`) was either not used as an immediate argument to Symbol("get") (argument matchers can only be used as an argument for the very method being stubbed or verified), or was used as a named argument without the Mocktail "named" API (Each argument matcher that is used as a named argument needs to specify the name of the argument it is being used in. For example: `when(() => obj.fn(x: any(named: "x")))`).

```
class MockHttpClient extends Mock implements http.Client {}

void main() {
  late MockHttpClient mockHttpClient;
  late HomeRemoteDataSourceImplementation homeRemoteDataSourceImplementation;

  setUp(() {
    mockHttpClient = new MockHttpClient();
    homeRemoteDataSourceImplementation =
        new HomeRemoteDataSourceImplementation(client: mockHttpClient);
  });

  group("getMedicalRecords", () {
    test(("should perform a GET request on a URL with application/json header"),
        () {
      when(() => mockHttpClient.get(Uri.parse(any()),
          headers: any(named: "headers"))).thenAnswer(
        (_) async =>
            http.Response(fixtures("Home/fixtures/medical_record.json"), 200),
      );

      homeRemoteDataSourceImplementation.getMedicalRecord();

      verify(
        () => mockHttpClient.get(
          Uri.parse(
              "https://run.mocky.io/v3/30579b01-75f8-4c9f-ac83-c98b5cfe1d2e"),
          headers: {
            "Content-Type": "application/json",
          },
        ),
      );
    });
  });
}
```

**Comment by mousedownmike** [comment] 2021-12-29 15:02
Your matchers on the mockHttpClient.get call are mixed. Replace `Uri.parse(any())` with `any()` like so:

```
when(() => mockHttpClient.get(any(),
          headers: any(named: "headers"))).thenAnswer(
        (_) async =>
            http.Response(fixtures("Home/fixtures/medical_record.json"), 200),
```

**Comment by raxahai** [comment] 2021-12-29 15:16
Did this as per your suggestion:

```
when(() => mockHttpClient.get(
            // Uri.parse(// cant use any as null exception
            //     "https://run.mocky.io/v3/30579b01-75f8-4c9f-ac83-c98b5cfe1d2e"),
            any(),
            headers: any(named: "headers"),
          )).thenAnswer(
        (_) async => http.Response(
            fixtures("features/Home/fixtures/medical_record.json"), 200),
      );
```


Bad state: A test tried to use `any` or `captureAny` on a parameter of type `Uri`, but
registerFallbackValue was not previously called to register a fallback value for `Uri`.

To fix, do:

```
void main() {
  setUpAll(() {
    registerFallbackValue(/* create a dummy instance of `Uri` */);
  });
}
```

**Comment by mousedownmike** [comment] 2021-12-29 15:49
Yes, you need a "Fake" Uri as [described in the README](https://github.com/felangel/mocktail/tree/main/packages/mocktail#how-it-works).  There's a good example in the `bloc` library `weather` example's [meta_weather_api_client_test](https://github.com/felangel/bloc/blob/master/examples/flutter_weather/packages/meta_weather_api/test/meta_weather_api_client_test.dart)

To get it going you would want to add something like:
```dart
class FakeUri extends Fake implements Uri {}
void main() {
    setUpAll(() {
      registerFallbackValue(FakeUri());
    });

/* ... your tests ... */
}
```

**Comment by n1h41** [comment] 2022-06-17 04:45
> Yes, you need a "Fake" Uri as [described in the README](https://github.com/felangel/mocktail/tree/main/packages/mocktail#how-it-works). There's a good example in the `bloc` library `weather` example's [meta_weather_api_client_test](https://github.com/felangel/bloc/blob/master/examples/flutter_weather/packages/meta_weather_api/test/meta_weather_api_client_test.dart)
> 
> To get it going you would want to add something like:
> 
> ```dart
> class FakeUri extends Fake implements Uri {}
> void main() {
>     setUpAll(() {
>       registerFallbackValue(FakeUri());
>     });
> 
> /* ... your tests ... */
> }
> ```

Hey, how can I create a registerFallbackValue for an enum ?

**Comment by felangel** [comment] 2022-06-17 04:56
> > Yes, you need a "Fake" Uri as [described in the README](https://github.com/felangel/mocktail/tree/main/packages/mocktail#how-it-works). There's a good example in the `bloc` library `weather` example's [meta_weather_api_client_test](https://github.com/felangel/bloc/blob/master/examples/flutter_weather/packages/meta_weather_api/test/meta_weather_api_client_test.dart)
> > To get it going you would want to add something like:
> > ```dart
> > class FakeUri extends Fake implements Uri {}
> > void main() {
> >     setUpAll(() {
> >       registerFallbackValue(FakeUri());
> >     });
> > 
> > /* ... your tests ... */
> > }
> > ```
> 
> Hey, how can I create a registerFallbackValue for an enum ?

You can just pass any enum value, no need to create a fake.

**Comment by n1h41** [comment] 2022-06-17 04:59
> > > Yes, you need a "Fake" Uri as [described in the README](https://github.com/felangel/mocktail/tree/main/packages/mocktail#how-it-works). There's a good example in the `bloc` library `weather` example's [meta_weather_api_client_test](https://github.com/felangel/bloc/blob/master/examples/flutter_weather/packages/meta_weather_api/test/meta_weather_api_client_test.dart)
> > > To get it going you would want to add something like:
> > > ```dart
> > > class FakeUri extends Fake implements Uri {}
> > > void main() {
> > >     setUpAll(() {
> > >       registerFallbackValue(FakeUri());
> > >     });
> > > 
> > > /* ... your tests ... */
> > > }
> > > ```
> > 
> > 
> > Hey, how can I create a registerFallbackValue for an enum ?
> 
> You can just pass any enum value, no need to create a fake.

`Bad state: A test tried to use `any` or `captureAny` on a parameter of type `METHOD`, but
registerFallbackValue was not previously called to register a fallback value for `METHOD`.

To fix, do:

```
void main() {
  setUpAll(() {
    registerFallbackValue(/* create a dummy instance of `METHOD` */);
  });
}
```

This instance of `METHOD` will only be passed around, but never be interacted with.
Therefore, if `METHOD` is a function, it does not have to return a valid object and
could throw unconditionally.
If you cannot easily create an instance of `METHOD`, consider defining a `Fake`:

```
class MyTypeFake extends Fake implements MyType {}

void main() {
  setUpAll(() {
    registerFallbackValue(MyTypeFake());
  });
}
````

This is the error I am getting while trying to pass the enum value

**Comment by felangel** [comment] 2022-06-17 12:25
@n1h41 can’t you provide a minimal reproduction sample?

**Comment by n1h41** [comment] 2022-06-17 16:22
> @n1h41 can’t you provide a minimal reproduction sample?

as you mentioned before I passed the enum value without creating the fake. It's working. Thanks

**Comment by alestiago** [comment] 2023-01-30 10:32
@raxahai I see that you've re-opened the issue. Do you still have an error? If so, can you provide minimal reproductive code (without external package dependencies besides mocktail)? Else can the issue be closed?

**Comment by djilet** [comment] 2024-01-30 09:29
it happens when i am using any() inside Record

**Comment by djilet** [comment] 2024-01-30 09:31
it happens when i am using any() inside Record

**Comment by felangel** [comment] 2024-04-20 03:54
Closing this for now since the issue is quite old and there aren't any actionable next steps. If anyone is still facing an issue please file a new bug and provide a minimal reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2024-04-20 03:54 UTC
Labels: question, waiting for response
