### ISSUE TITLE
Using when() cause The argument type 'Either<Failure, int>' can't be assigned to the parameter type 'dynamic Function()'

### ISSUE THREAD

**Issue by diazsasak** [felangel/mocktail#89] opened 2021-11-01 13:12 UTC
**Describe the bug**
I want to stub my mock method using when(), but it show error

**To Reproduce**

1. Here is my class
`class InputConverter {
  Either<Failure, int> stringToUnsignedInteger(String str) {
    int? val = int.tryParse(str);
    if (val == null || val.isNegative) {
      return Left(InvalidInputFailure());
    }
    return Right(val);
  }
}`
2. Create mock and create instance of it

`class MockInputConverter extends Mock implements InputConverter {}`

3. create stub
`when(mockInputConverter.stringToUnsignedInteger(any))
          .thenReturn(Right(numberParsed));`

**Expected behavior**
I expect it has no error, it work previously if using mockito

i am using mocktail: ^0.2.0

Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-ID)
    • Flutter version 2.5.3 at /Users/diazfebrian/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

**Comment by felangel** [comment] 2021-11-01 14:32
Hi @diazsasak 👋 
Thanks for opening an issue!

I believe the issue is you need to pass a closure to `when` like:

```dart
when(() => mockInputConverter.stringToUnsignedInteger(any()).thenReturn(Right(numberParsed));
```

Let me know if that helps 👍

**Comment by diazsasak** [comment] 2021-11-01 22:46
Hi @felangel ,
Thank you for your response.

yes that solve the problem for when(), and for untilCalled() and verify() also. 

but i got another error on any. any suggestion?

`
when(() => mockInputConverter.stringToUnsignedInteger(any))
          .thenReturn(Right(numberParsed));

      numberTriviaBloc.add(GetTriviaForConcreteNumber(numberString));

      await untilCalled(() => mockInputConverter.stringToUnsignedInteger(any));

      verify(() => mockInputConverter.stringToUnsignedInteger(numberString));
`

the error is
`
The argument type 'T Function<T>({String? named, Matcher? that})' can't be assigned to the parameter type 'String'
`

![image](https://user-images.githubusercontent.com/7880137/139751932-f129385d-6a41-4c7a-9b62-9f8cd8e23dc5.png)

**Comment by felangel** [comment] 2021-11-02 03:39
> Hi @felangel , Thank you for your response.
> 
> yes that solve the problem for when(), and for untilCalled() and verify() also.
> 
> but i got another error on any. any suggestion?
> 
> ` when(() => mockInputConverter.stringToUnsignedInteger(any)) .thenReturn(Right(numberParsed));
> 
> ```
>   numberTriviaBloc.add(GetTriviaForConcreteNumber(numberString));
> 
>   await untilCalled(() => mockInputConverter.stringToUnsignedInteger(any));
> 
>   verify(() => mockInputConverter.stringToUnsignedInteger(numberString));
> ```
> 
> `
> 
> the error is `The argument type 'T Function<T>({String? named, Matcher? that})' can't be assigned to the parameter type 'String'`
> 
> ![image](https://user-images.githubusercontent.com/7880137/139751932-f129385d-6a41-4c7a-9b62-9f8cd8e23dc5.png)

`any` is a function so it should be `any()` instead of `any`. Hope that helps 👍

**Comment by felangel** [comment] 2021-11-07 04:19
Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-11-07 04:19 UTC
Labels: question, waiting for response

**Comment by diazsasak** [comment] 2021-11-07 09:14
Ok got it. Thank you for your help @felangel
