### ISSUE TITLE
dart 2.19 doesn't delegate inaccessible private names to noSuchMethod.

### ISSUE THREAD

**Issue by amondnet** [felangel/mocktail#159] opened 2022-10-19 01:22 UTC
**Is your feature request related to a problem? Please describe.**

Dart 2.19 doesn't delegate inaccessible private names to noSuchMethod.

https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#2190
https://github.com/dart-lang/language/issues/2020
https://github.com/dart-lang/sdk/issues/49687
https://github.com/dart-lang/site-www/issues/4263

https://github.com/mobxjs/mobx.dart/blob/master/mobx/test/observable_test.dart
The test fails on dart 2.19.

https://github.com/mobxjs/mobx.dart/actions/runs/3262020308/jobs/5359681093

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by felangel** [comment] 2022-10-19 04:14
Hi @amondnet 👋 
Thanks for opening an issue!

Are you able to provide a minimal reproduction sample? If not, I can try to take a look at the mobx tests shortly but it would be much easier if you were able to provide a minimal reproduction sample without any additional dependencies/complexity. Thanks!

**Comment by felangel** [comment] 2022-10-21 02:30
@amondnet I just tested with the Dart dev release (`Dart SDK version: 2.19.0-318.0.dev (dev) (Tue Oct 18 13:21:13 2022 -0700) on "macos_arm64"`) and was not able to reproduce. What's the exact version of Dart you're using?

**Comment by amondnet** [comment] 2022-10-21 14:12
@felangel 

Yes, as you already know, we can call private methods in the same file.

The tests work fine if they are in the same file. But if I split the file, test fails.

https://github.com/amondnet/mocktail_dart_2_19/blob/main/lib/mocktail_dart_2_19.dart
https://github.com/amondnet/mocktail_dart_2_19/blob/main/test/same_file_test.dart

https://github.com/amondnet/mocktail_dart_2_19/actions/runs/3298075777

> ```dart
> @visibleForTesting
> mixin MockContextMixin implements Context {
>   void _reportObserved(Observable atom) {}
> }
> 
> class MockContext extends Mock with MockContextMixin implements Context {}
> 
> void main() {
>   test('test', () {
>     final context = MockContext();
> 
>     final observable = Observable(1, context)..value += 1;
>     expect(observable.value, 2);
>   });
> }
> 
> ```

The above test also fails.

**Comment by felangel** [comment] 2022-10-21 14:22
> @felangel
> 
> Yes, as you already know, we can call private methods in the same file.
> 
> The tests work fine if they are in the same file.
> 
> https://github.com/amondnet/mocktail_dart_2_19/blob/main/test/same_file_test.dart
> 
> But if I split the file, test fails.
> 
> https://github.com/amondnet/mocktail_dart_2_19/blob/main/lib/mocktail_dart_2_19.dart https://github.com/amondnet/mocktail_dart_2_19/blob/main/test/other_file_test.dart
> 
> https://github.com/amondnet/mocktail_dart_2_19/actions/runs/3298075777
> 
> > ```dart
> > @visibleForTesting
> > mixin MockContextMixin implements Context {
> >   void _reportObserved(Observable atom) {}
> > }
> > 
> > class MockContext extends Mock with MockContextMixin implements Context {}
> > 
> > void main() {
> >   test('test', () {
> >     final context = MockContext();
> > 
> >     final observable = Observable(1, context)..value += 1;
> >     expect(observable.value, 2);
> >   });
> > }
> > ```
> 
> The above test also fails.

What’s the exact version of Dart you are using?

**Comment by amondnet** [comment] 2022-10-21 14:32
@felangel

https://github.com/amondnet/mocktail_dart_2_19/actions/runs/3298075777/jobs/5439719989

Dart SDK version: 2.19.0-255.2.beta (beta) (Tue Oct 4 13:45:53 2022 +0200) on "linux_x64" : fail
Dart SDK version: 2.19.0-318.0.dev (dev) (Tue Oct 18 13:21:13 2022 -0700) on "linux_x64" : fail

Dart SDK version: 2.19.0-255.2.beta (beta) (Tue Oct 4 13:45:53 2022 +0200) on "macos_x64": fail
Dart SDK version: 2.19.0-318.0.dev (dev) (Tue Oct 18 13:21:13 2022 -0700) on "macos_x64" : fail

Also, the test fails equally when using [mockito](https://pub.dev/packages/mockito/example).

**Comment by felangel** [comment] 2022-10-21 15:29
@amondnet I think the proper thing to do in this case is refactor `mobx` so that `reportObserved` is `protected` instead of private. There's not really much that `mocktail` or `mockito` can do in this case unfortunately.

**Comment by felangel** [comment] 2022-10-25 20:22
Closing for now since there are no actionable steps to be taken in mocktail.

**Closed by felangel** 2022-10-25 20:22 UTC
Labels: question, waiting for response
