### ISSUE TITLE
Support the latest Analyzer

### ISSUE THREAD

**Issue by wer-mathurin** [felangel/mocktail#166] opened 2022-11-22 20:06 UTC
@felangel 
The current dependency to 
test: ^1.16.0 that rely on an old analyzer version

any plan to upgrade to at least 
test: ^1.21.6

**Comment by elias8** [comment] 2022-11-26 21:39
Hi @felangel 👋

`mocktail` is causing a conflict with other dependencies because of the outdated `test` package it depends on. In my case, removing/disabling `mocktail` fixes the issue. See the attached screenshot for more info. In the meantime, I can open a PR for it. 



<img width="1743" alt="Screenshot 2022-11-27 at 12 27 51 AM" src="https://user-images.githubusercontent.com/18151864/204109892-7862b901-10e3-40ba-9126-0e49769b3472.png">

**Comment by felangel** [comment] 2022-11-26 22:16
@elias8 this looks like a duplicate of https://github.com/flutter/flutter/issues/115284.

**Comment by elias8** [comment] 2022-11-26 22:40
> @elias8 this looks like a duplicate of [flutter/flutter#115284](https://github.com/flutter/flutter/issues/115284).

Yeah. I tried to upgrade `mocktail` dependencies and doesn't seem to fix the issue.

**Comment by felangel** [comment] 2022-11-26 22:40
Closing since this is a duplicate of https://github.com/flutter/flutter/issues/115284 and has been fixed but hasn’t yet made it to the stable Flutter channel afaik

**Closed by felangel** 2022-11-26 22:40 UTC
Labels: question, waiting for response
