### ISSUE TITLE
How to stub toString() for a mocked class

### ISSUE THREAD

**Issue by Wizzel1** [felangel/mocktail#126] opened 2022-04-14 09:12 UTC
I am trying to Mock a `Node` class and stub the `toString()` method. 

When I run the test I am geting an Error 

```
Bad state: No method stub was called from within `when()`. Was a real method called, or perhaps an extension method?
``` 

which is probably because the Mock class has a `toString()` method by itself.

Is there a recommended workaround?

This is my Code : 

```dart 

class MockNode extends Mock implements Node {}

void main() {
    late MockNode mockNode;
    const nodeListString = '''
    [log] § {{list: Attribute{key: list, scope: AttributeScope.BLOCK, value: ordered}}}
        ├ ¶ ⟨Test⟩bold ⏎ {Attribute{key: list, scope: AttributeScope.BLOCK, value: ordered}}
        └ ¶ ⟨Test⟩italic ⏎ {Attribute{key: list, scope: AttributeScope.BLOCK, value: ordered}}
    ''';

    setUp(() {
      mockNode = MockNode();
      when(mockNode.toString).thenReturn(nodeListString);
    });
  
    test('returns a list of items', () {
      final items = DeltaToPdfConverter().getListItemsFromNode(node: mockNode);
      expect(items.length, 2);
     });

  }
  ```

**Comment by tomsitter** [comment] 2022-04-21 03:50
You call `when` like this: `when(() => mockNode.toString()).thenReturn(nodeListString);`

**Comment by Wizzel1** [comment] 2022-04-21 07:14
Thanks, but that doesn't solve my problem unfortunately

**Comment by felangel** [comment] 2022-04-21 15:43
@Wizzel1 can you provide a link to a complete, minimal reproduction sample? Thanks!

**Comment by Wizzel1** [comment] 2022-04-22 06:42
Add the latest version of  [flutter_quill](https://pub.dev/packages/flutter_quill)  to your dependencies

```dart
import 'package:flutter_quill/src/models/documents/nodes/node.dart' show Node;

class MockNode extends Mock implements Node {}

void main() {
 late MockNode mockNode;

  setUp(() {
    mockNode = MockNode();
  });
  
  test('returns value of tostring', () {
      when(() => mockNode.toString()).thenReturn('test');
      // in my case, I am passing the mocknode to a function that calls .toString() on it.
      final value = mockNode.toString();
      expect(value, 'test');
  });
}
```

**Comment by felangel** [comment] 2022-06-09 04:01
Hi @Wizzel1 👋 
This is because in this case the `Mock` class overrides `toString` so when you're stubbing `toString` in the `when` you're trying to `stub` the real `toString` implementation. In this case, I'd highly recommend using a real `Node` instance to verify the `toString()`.

Closing for now but feel free to comment with additional questions/comments and I'm happy to continue the conversation 👍

**Closed by felangel** 2022-06-09 04:01 UTC
Labels: question, waiting for response
